# Generated by Django 4.1.3 on 2024-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_word_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
    ]
