# Generated by Django 4.1.3 on 2024-06-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image_remove_word_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='word',
        ),
    ]
