# Generated by Django 4.1.3 on 2024-06-05 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_productdetails_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('itemname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_quantity', models.IntegerField()),
                ('image', models.JSONField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
